# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.

# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

from facebook_business.adobjects.abstractobject import AbstractObject

"""
This class is auto-generated.

For any issues or feature requests related to this class, please let us know on
github and we'll fix in our codegen framework. We'll not be able to accept
pull request for this class.
"""

class BusinessRecommendationsGet(
    AbstractObject,
):

    def __init__(self, api=None):
        super(BusinessRecommendationsGet, self).__init__()
        self._isBusinessRecommendationsGet = True
        self._api = api

    class Field(AbstractObject.Field):
        data = 'data'
        paging = 'paging'
        summary = 'summary'

    class Locale:
        af_za = 'AF_ZA'
        ak_gh = 'AK_GH'
        am_et = 'AM_ET'
        ar_ar = 'AR_AR'
        as_in = 'AS_IN'
        ay_bo = 'AY_BO'
        az_az = 'AZ_AZ'
        be_by = 'BE_BY'
        bg_bg = 'BG_BG'
        bm_ml = 'BM_ML'
        bn_in = 'BN_IN'
        bp_in = 'BP_IN'
        br_fr = 'BR_FR'
        bs_ba = 'BS_BA'
        bv_de = 'BV_DE'
        ca_es = 'CA_ES'
        cb_iq = 'CB_IQ'
        ck_us = 'CK_US'
        co_fr = 'CO_FR'
        cs_cz = 'CS_CZ'
        cx_ph = 'CX_PH'
        cy_gb = 'CY_GB'
        da_dk = 'DA_DK'
        de_de = 'DE_DE'
        eh_in = 'EH_IN'
        el_gr = 'EL_GR'
        em_zm = 'EM_ZM'
        en_gb = 'EN_GB'
        en_in = 'EN_IN'
        en_op = 'EN_OP'
        en_pi = 'EN_PI'
        en_ud = 'EN_UD'
        en_us = 'EN_US'
        en_xa = 'EN_XA'
        eo_eo = 'EO_EO'
        es_cl = 'ES_CL'
        es_co = 'ES_CO'
        es_es = 'ES_ES'
        es_la = 'ES_LA'
        es_mx = 'ES_MX'
        es_ve = 'ES_VE'
        et_ee = 'ET_EE'
        eu_es = 'EU_ES'
        fa_ir = 'FA_IR'
        fbt_ac = 'FBT_AC'
        fb_aa = 'FB_AA'
        fb_ac = 'FB_AC'
        fb_ar = 'FB_AR'
        fb_ha = 'FB_HA'
        fb_hx = 'FB_HX'
        fb_ll = 'FB_LL'
        fb_ls = 'FB_LS'
        fb_lt = 'FB_LT'
        fb_rl = 'FB_RL'
        fb_zh = 'FB_ZH'
        ff_ng = 'FF_NG'
        fi_fi = 'FI_FI'
        fn_it = 'FN_IT'
        fo_fo = 'FO_FO'
        fr_ca = 'FR_CA'
        fr_fr = 'FR_FR'
        fv_ng = 'FV_NG'
        fy_nl = 'FY_NL'
        ga_ie = 'GA_IE'
        gl_es = 'GL_ES'
        gn_py = 'GN_PY'
        gu_in = 'GU_IN'
        gx_gr = 'GX_GR'
        ha_ng = 'HA_NG'
        he_il = 'HE_IL'
        hi_fb = 'HI_FB'
        hi_in = 'HI_IN'
        hr_hr = 'HR_HR'
        ht_ht = 'HT_HT'
        hu_hu = 'HU_HU'
        hy_am = 'HY_AM'
        id_id = 'ID_ID'
        ig_ng = 'IG_NG'
        ik_us = 'IK_US'
        is_is = 'IS_IS'
        it_it = 'IT_IT'
        iu_ca = 'IU_CA'
        ja_jp = 'JA_JP'
        ja_ks = 'JA_KS'
        jv_id = 'JV_ID'
        ka_ge = 'KA_GE'
        kk_kz = 'KK_KZ'
        km_kh = 'KM_KH'
        kn_in = 'KN_IN'
        ko_kr = 'KO_KR'
        ks_in = 'KS_IN'
        ku_tr = 'KU_TR'
        ky_kg = 'KY_KG'
        la_va = 'LA_VA'
        lg_ug = 'LG_UG'
        li_nl = 'LI_NL'
        ln_cd = 'LN_CD'
        lo_la = 'LO_LA'
        lr_it = 'LR_IT'
        lt_lt = 'LT_LT'
        lv_lv = 'LV_LV'
        mg_mg = 'MG_MG'
        mi_nz = 'MI_NZ'
        mk_mk = 'MK_MK'
        ml_in = 'ML_IN'
        mn_mn = 'MN_MN'
        mos_bf = 'MOS_BF'
        mr_in = 'MR_IN'
        ms_my = 'MS_MY'
        mt_mt = 'MT_MT'
        my_mm = 'MY_MM'
        nb_no = 'NB_NO'
        nd_zw = 'ND_ZW'
        ne_np = 'NE_NP'
        nh_mx = 'NH_MX'
        nl_be = 'NL_BE'
        nl_nl = 'NL_NL'
        nn_no = 'NN_NO'
        nr_za = 'NR_ZA'
        ns_za = 'NS_ZA'
        ny_mw = 'NY_MW'
        om_et = 'OM_ET'
        or_in = 'OR_IN'
        pa_in = 'PA_IN'
        pcm_ng = 'PCM_NG'
        pl_pl = 'PL_PL'
        ps_af = 'PS_AF'
        pt_br = 'PT_BR'
        pt_pt = 'PT_PT'
        qb_de = 'QB_DE'
        qc_gt = 'QC_GT'
        qe_us = 'QE_US'
        qk_dz = 'QK_DZ'
        qr_gr = 'QR_GR'
        qs_de = 'QS_DE'
        qt_us = 'QT_US'
        qu_pe = 'QU_PE'
        qv_it = 'QV_IT'
        qz_mm = 'QZ_MM'
        rm_ch = 'RM_CH'
        rn_bi = 'RN_BI'
        ro_ro = 'RO_RO'
        ru_ru = 'RU_RU'
        rw_rw = 'RW_RW'
        sa_in = 'SA_IN'
        sc_it = 'SC_IT'
        se_no = 'SE_NO'
        si_lk = 'SI_LK'
        sk_sk = 'SK_SK'
        sl_si = 'SL_SI'
        sn_zw = 'SN_ZW'
        so_so = 'SO_SO'
        sq_al = 'SQ_AL'
        sr_rs = 'SR_RS'
        ss_sz = 'SS_SZ'
        st_za = 'ST_ZA'
        su_id = 'SU_ID'
        sv_se = 'SV_SE'
        sw_ke = 'SW_KE'
        sy_sy = 'SY_SY'
        sz_pl = 'SZ_PL'
        ta_in = 'TA_IN'
        te_in = 'TE_IN'
        tg_tj = 'TG_TJ'
        th_th = 'TH_TH'
        ti_et = 'TI_ET'
        tk_tm = 'TK_TM'
        tl_ph = 'TL_PH'
        tl_st = 'TL_ST'
        tn_bw = 'TN_BW'
        tpi_pg = 'TPI_PG'
        tq_ar = 'TQ_AR'
        tr_tr = 'TR_TR'
        ts_za = 'TS_ZA'
        tt_ru = 'TT_RU'
        tz_ma = 'TZ_MA'
        uk_ua = 'UK_UA'
        ur_pk = 'UR_PK'
        uz_uz = 'UZ_UZ'
        ve_za = 'VE_ZA'
        vi_vn = 'VI_VN'
        wo_sn = 'WO_SN'
        xh_za = 'XH_ZA'
        yi_de = 'YI_DE'
        yo_ng = 'YO_NG'
        zh_cn = 'ZH_CN'
        zh_hk = 'ZH_HK'
        zh_tw = 'ZH_TW'
        zu_za = 'ZU_ZA'
        zz_tr = 'ZZ_TR'

    class Scopes:
        owned = 'OWNED'
        shared = 'SHARED'

    _field_types = {
        'data': 'list<object>',
        'paging': 'object',
        'summary': 'object',
    }
    @classmethod
    def _get_field_enum_info(cls):
        field_enum_info = {}
        field_enum_info['Locale'] = BusinessRecommendationsGet.Locale.__dict__.values()
        field_enum_info['Scopes'] = BusinessRecommendationsGet.Scopes.__dict__.values()
        return field_enum_info


